# Grafana datasource provisioning - Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://clab-kea-lab-prometheus-prometheus:9090
    isDefault: true
    editable: false
